---
title: "R6 Generator Maven Archetype: Recommended project setup"
author: "Rob Challen"
output: html_vignette
vignette: >
  %\VignetteIndexEntry{R6 Generator Maven Archetype: Recommended project setup}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  error = TRUE)


if (.Platform$OS.type == "windows") {
  
  # don't try evaluate this vignette
  # in windows as bash chunks don't always work
  knitr::opts_chunk$set(eval = FALSE)

} else {
  
  # stop this from being run if not being run as part of build_site()
  # this should stop it from running on CRAN and in github worflows
  inPkgdown = identical(Sys.getenv("IN_PKGDOWN"), "true")
  knitr::opts_chunk$set(eval = inPkgdown)
  
}
```

# Set up temporary location:

```{r}
dir = fs::path(tempdir(),"testProject")
fs::dir_create(dir)
Sys.setenv(TMP_DIR=dir)
dir

v = testRapi::JavaApi$versionInformation()
version = v$r_package_version
if (version=="0.0.0.9999") {
  version="main-SNAPSHOT"
  # as this is a web-only vignette we are assuming that this will work as it is being run on a development machine.
  # with a locally installed snapshot maven snapshot - to make this work on another machine we need to adjust settings.xml
  # to include sonatypes snapshot repository
}
Sys.setenv(TMP_VERSION=version)
version
```

## Maven archetype

```{bash}
cd $TMP_DIR
rm -r examplePackage ||: 
mvn archetype:generate -B \
  -DarchetypeGroupId=io.github.terminological \
  -DarchetypeArtifactId=r6-generator-maven-archetype \
  -DarchetypeVersion=$TMP_VERSION \
  -DgithubOrganisation=exampleOrganisation \
  -DgithubRepository=examplePackage
```

```{r}
fs::dir_tree(dir,regexp="((.*/target)|docs)/.*", invert=TRUE)
```

## Building the project

```{bash}
cd $TMP_DIR/examplePackage/java
mvn install
```

# Generated files:

```{r}
fs::dir_tree(dir,regexp="((.*/target)|docs)/.*", invert=TRUE)
```

# Package website:

```{r}
if (interactive()) 
  browseURL(paste0("file:/",URLencode(fs::path(dir,"examplePackage","docs","index.html"))))
```