# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for A Test Library}

library(testthat)
library(testRapi)

test_check("testRapi")