# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for testRapi::FactoryTest

# R6 FactoryTest instance methods ----

# ├ generateCharacter() R6 method ----
# ├ generateNumeric() R6 method ----
# ├ generateInteger() R6 method ----
# ├ generateFactor() R6 method ----
# ├ generateLogical() R6 method ----
# ├ generateCharacterVec() R6 method ----
# ├ generateNumericVec() R6 method ----
# ├ generateIntegerVec() R6 method ----
# ├ generateFactorVec() R6 method ----
# ├ generateLogicalVec() R6 method ----
# ├ generateDataframe() R6 method ----
# ├ generateStreamDataframe() R6 method ----
# ├ generateList() R6 method ----
# ├ generateNamedList() R6 method ----

# FactoryTest static methods ----

