# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rc538@exeter.ac.uk
# Automated tests for testRapi::MoreFeatureTest

# R6 MoreFeatureTest instance methods ----

# ├ testLogging() R6 method ----
# ├ throwCatchable() R6 method ----
# ├ printMessage() R6 method ----
# ├ throwRuntime() R6 method ----

# MoreFeatureTest static methods ----

# ├ create() package method ----
# ├ concat() package method ----
