# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for testRapi::BounceTest

# R6 BounceTest instance methods ----

# ├ bounceNull() R6 method ----
# ├ bounceVoid() R6 method ----
# ├ bounceString() R6 method ----
# ├ bounceCharacter() R6 method ----
# ├ bounceCharacterVector() R6 method ----
# ├ bounceDouble() R6 method ----
# ├ bounceNumeric() R6 method ----
# ├ bounceNumericVector() R6 method ----
# ├ bounceInt() R6 method ----
# ├ bounceInteger() R6 method ----
# ├ bounceIntegerVector() R6 method ----
# ├ bounceFactor() R6 method ----
# ├ bounceFactorVector() R6 method ----
# ├ bounceDate() R6 method ----
# ├ bounceDateVector() R6 method ----
# ├ bounceLogical() R6 method ----
# ├ bounceLogicalVector() R6 method ----
# ├ bounceDataframe() R6 method ----
# ├ bounceList() R6 method ----
# ├ bounceNamedList() R6 method ----
# ├ bounceArray() R6 method ----

# BounceTest static methods ----

