# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rc538@exeter.ac.uk
# Automated tests for testRapi::MoreFeatureTest

# R6 MoreFeatureTest instance methods ----

# ├ testLogging() R6 method ----
# ├ throwCatchable() R6 method ----
# ├ printMessage() R6 method ----
# ├ throwRuntime() R6 method ----

# MoreFeatureTest static methods ----

# ├ create() package method ----
# ├ concat() package method ----
# ├ more_feature_test_collider() package method ----
test_that("testRapi::more_feature_test_collider() static method", {
	tmp = more_feature_test_collider('should ','work')
	expect_equal(tmp,'more feature test: should work')
	expect_message(message("test case complete"))
})
