# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rc538@exeter.ac.uk
# Automated tests for testRapi::FeatureTest

# R6 FeatureTest instance methods ----

# ├ doHelloWorld() R6 method ----
# ├ doSum() R6 method ----
test_that("FeatureTest$doSum() R6 method",	{
	J = JavaApi$get()
	minExample = J$FeatureTest$new('Hello from Java constructor!')
	result = minExample$doSum(2,7.5)
	expect_equal(result,9.5)
})
# ├ doSum2() R6 method ----
# ├ getMessage() R6 method ----
# ├ fluentSetMessage() R6 method ----
# ├ factoryMethod() R6 method ----
# ├ objectAsParameter() R6 method ----
# ├ doSomethingWithDataFrame() R6 method ----
# ├ generateDataFrame() R6 method ----
# ├ errorThrower() R6 method ----

# FeatureTest static methods ----

# ├ demo_static() package method ----
# ├ diamonds() package method ----
test_that("testRapi::diamonds() static method", {
	expect_equal(diamonds(), ggplot2::diamonds)
})
