# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for testRapi::MoreFeatureTest

# R6 MoreFeatureTest instance methods ----

# ├ testLogging() R6 method ----
# ├ throwCatchable() R6 method ----
# ├ printMessage() R6 method ----
# ├ throwRuntime() R6 method ----

# MoreFeatureTest static methods ----

# ├ create() package method ----
# ├ concat() package method ----
# ├ collider.more_feature_test() package method ----
test_that("testRapi::collider.more_feature_test() static method", {
	tmp = collider.more_feature_test('should ','work')
	expect_equal(tmp,'more feature test: should work')
	expect_message(message("test case complete"))
})
