# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for testRapi::Serialiser

# R6 Serialiser instance methods ----


# Serialiser static methods ----

# ├ serialise_dataframe() package method ----
# ├ deserialise_dataframe() package method ----
# ├ serialise_list() package method ----
# ├ deserialise_list() package method ----
# ├ serialise_named_list() package method ----
# ├ deserialise_named_list() package method ----
