# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: rob@terminological.co.uk
# Automated tests for testRapi::MinimalExample

# R6 MinimalExample instance methods ----

# ├ demo() R6 method ----

# MinimalExample static methods ----

