# Generated by r6-generator-maven-plugin: do not edit by hand
#' This is the main entry point of the testRapi generated R library.
#'
#' @description
#' A Test Library
#'
#' Version: 1.1.0
#'
#' Generated: 2024-05-16T16:22:15.406821417
#'
#' Contact: rob@terminological.co.uk
#' @import R6
#' @import ggplot2
#' @import readr
#' @import tibble
#' @import dplyr
#' @import rJava 
#' @export
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	#' @field .log a pointer to the java logging system
	.log = NULL,
	#' @field .fromJava a set of type conversion functions from Java to R
	.fromJava = NULL,
	#' @field .toJava a set of type conversion functions from R to Java
	.toJava = NULL,
	#' @field .reg the list of references to java objects created by this API 
	.reg = list(),
	#' @field MinimalExample the MinimalExample class constructors and static methods
	MinimalExample = NULL,
	#' @field BounceTest the BounceTest class constructors and static methods
	BounceTest = NULL,
	#' @field FeatureTest the FeatureTest class constructors and static methods
	FeatureTest = NULL,
	#' @field MoreFeatureTest the MoreFeatureTest class constructors and static methods
	MoreFeatureTest = NULL,
	#' @field FactoryTest the FactoryTest class constructors and static methods
	FactoryTest = NULL,
	#' @field Serialiser the Serialiser class constructors and static methods
	Serialiser = NULL,

	#' @description
	#' change the java logging level
	#' @param logLevel A string such as "DEBUG", "INFO", "WARN"
	#' @return nothing
	changeLogLevel = function(logLevel) {
		.jcall("uk/co/terminological/rjava/RLogController", returnSig = "V", method = "changeLogLevel" , logLevel)
		invisible(NULL)
	},
	
	#' @description
	#' change the java logging level using a log4j configuration file
	#' @param log4jproperties An absolute filepath to the log4j propertied file
	#' @return nothing
	reconfigureLog = function(log4jproperties) {
		.jcall("uk/co/terminological/rjava/RLogController", returnSig = "V", method = "reconfigureLog" , log4jproperties)
		invisible(NULL)
	},
	
	#' @description
	#' print java system messages to the R console and flush the message cache. This is generally called automatically,
	#' @return nothing
	printMessages = function() {
		# check = FALSE here to stop exceptions being cleared from the stack.
		msg = .jcall("uk/co/terminological/rjava/RSystemOut", returnSig = "Ljava/lang/String;", method = "getSystemMessages", check=FALSE)
		.message(msg)
		invisible(NULL)
	},
	
 	#### constructor ----
 	#' @description
 	#' Create the R6 api library class. This is the entry point to all Java related classes and methods in this package.
	#' @param logLevel One of "OFF", "FATAL", "ERROR", "WARN", "INFO", "DEBUG", "TRACE", "ALL". (defaults to "INFO") 
	#' @examples
	#' J = testRapi::JavaApi$get();
	#' @return nothing
 	initialize = function(logLevel = "INFO") {
 		if (is.null(JavaApi$singleton)) stop("Startup the java api with JavaApi$get() rather than using this constructor directly")
 	
 	
 		.startJvm()
		
		# Java dependencies
		jars = .checkDependencies(quiet = TRUE)
		.jaddClassPath(jars)
		
		# configure system console and logging
 		.jcall("uk/co/terminological/rjava/RSystemOut", returnSig = "V", method = "setup")
 		.jcall("uk/co/terminological/rjava/RLogController", returnSig = "V", method = "configureLog" , logLevel)
 		# TODO: this is the library build date code but it requires testing
 		buildDate = .jcall("uk/co/terminological/rjava/RLogController", returnSig = "S", method = "getClassBuildTime")
		self$.log = .jcall("org/slf4j/LoggerFactory", returnSig = "Lorg/slf4j/Logger;", method = "getLogger", "testRapi");
		.jcall(self$.log,returnSig = "V",method = "debug", "Adding to classpath: ")
		for (jar in jars) {
		  .jcall(self$.log,returnSig = "V",method = "debug", jar)
		}
		.jcall(self$.log,returnSig = "V",method = "info","Initialised testRapi");
		.jcall(self$.log,returnSig = "V",method = "debug","R package version: 1.1.0");
		.jcall(self$.log,returnSig = "V",method = "debug","R package generated: 2024-05-16T16:22:15.407409258");
		.jcall(self$.log,returnSig = "V",method = "debug","Java library version: io.github.terminological:r6-generator-docs:1.1.0");
		.jcall(self$.log,returnSig = "V",method = "debug",paste0("Java library compiled: ",buildDate));
		.jcall(self$.log,returnSig = "V",method = "debug","Contact: rob@terminological.co.uk");
		self$printMessages()
		
		# initialise type conversion functions
		
		self$.toJava = list(
			RNumericArray=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				if (!is.array(rObj)) stop('expected an array')
				tmpVec = as.vector(as.numeric(rObj))
				tmpDim = dim(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericArray',rJava::.jarray(tmpVec),rJava::.jarray(tmpDim)))
			},
			RDate=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RDate'))
				if (length(rObj) > 1) stop('input too long')
			   if (rObj<'0001-01-01') cli::cli_inform('dates smaller than 0001-01-01 will be converted to NA')
				tmp = format(rObj,format='%C%y-%m-%d')[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDate',tmp))
			},
			RDateVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RDateVector'))
				if (any(na.omit(rObj)<'0001-01-01')) cli::cli_inform('dates smaller than 0001-01-01 will be converted to NA')
				tmp = format(rObj,format='%C%y-%m-%d')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RDateVector',rJava::.jarray(tmp)))
			},
			RCharacterVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector'))
				if (!is.character(rObj)) stop('expected a vector of characters')
				tmp = as.character(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacterVector',rJava::.jarray(tmp)))
			},
			FeatureTest=function(rObj) return(rObj$.jobj),
			RNumeric=function(rObj) {
				if (length(rObj) > 1) stop('input too long')
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumeric',tmp))
			},
			RLogical=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical'))
				if (length(rObj) > 1) stop('input too long')
				if (!is.logical(rObj)) stop('expected a logical')
				tmp = as.integer(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogical',tmp))
			},
			RFactor=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				tmpLabel = levels(rObj)[[tmp]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactor',tmp, tmpLabel))
			},
			RNull=function(rObj) {
				if (!is.null(rObj)) stop('input expected to be NULL')
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNull'))
			},
			RLogicalVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector'))
				if (!is.logical(rObj)) stop('expected a vector of logicals')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RLogicalVector',rJava::.jarray(tmp)))
			},
			RCharacter=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter'))
				tmp = as.character(rObj)[[1]]
				return(rJava::.jnew('uk/co/terminological/rjava/types/RCharacter',tmp))
			},
			Serialiser=function(rObj) return(rObj$.jobj),
			String=function(rObj) return(as.character(rObj)),
			MinimalExample=function(rObj) return(rObj$.jobj),
			FactoryTest=function(rObj) return(rObj$.jobj),
			void=function(rObj) stop('no input expected'),
			double=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java double')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.numeric(rObj)) stop('not an double')
			    return(as.numeric(rObj[[1]]))
			},
			RList=function(rObj) {
			   if (!is.list(rObj)) stop ('expecting a list ')
			   if (!is.null(names(rObj))) warning('not expecting list to be named')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RList')
				lapply(rObj, function(x) {
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Z',method='add',rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			},
			RNumericVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector'))
				if (!is.numeric(rObj)) stop('expected a numeric')
				tmp = as.numeric(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RNumericVector',rJava::.jarray(tmp)))
			},
			BounceTest=function(rObj) return(rObj$.jobj),
			int=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java int')
			    if (length(rObj) > 1) stop('input too long')
			    if (as.integer(rObj)[[1]]!=rObj[[1]]) stop('not an integer')
			    return(as.integer(rObj[[1]]))
			},
			boolean=function(rObj) {
			    if (is.na(rObj)) stop('cant use NA as input to java boolean')
			    if (length(rObj) > 1) stop('input too long')
			    if (!is.logical(rObj)) stop('not a logical')
			    return(as.logical(rObj[[1]]))
			},
			RInteger=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger'))
				if (length(rObj) > 1) stop('input too long')
				tmp = as.integer(rObj)[[1]]
				if (rObj[[1]]!=tmp) stop('cannot cast to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RInteger',tmp))
			},
			RBoundDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RDataframe=function(rObj) {
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RDataframe')
				lapply(colnames(rObj), function(x) {
					rcol = rObj[[x]]
					if(is.character(rcol)) jvec = self$.toJava$RCharacterVector(rcol)
					else if(is.integer(rcol)) jvec = self$.toJava$RIntegerVector(rcol)
					else if(is.factor(rcol)) jvec = self$.toJava$RFactorVector(rcol)
					else if(is.logical(rcol)) jvec = self$.toJava$RLogicalVector(rcol)
					else if(is.numeric(rcol)) jvec = self$.toJava$RNumericVector(rcol)
					else if(inherits(rcol,c('Date','POSIXt'))) jvec = self$.toJava$RDateVector(rcol)
					else stop('unsupported data type in column: ',x)
					rJava::.jcall(jout,returnSig='V',method='addCol',x,rJava::.jcast(jvec,new.class='uk/co/terminological/rjava/types/RVector'))
				})
				rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RDataframe;',method='groupBy',rJava::.jarray(dplyr::group_vars(rObj)))
				return(jout)
			},
			RUntypedNaVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.new('uk/co/terminological/rjava/types/RUntypedNaVector'))
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNaVector',length(rObj)))
			},
			RFile=function(rObj) {
				if (is.na(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFile'))
				if (length(rObj) > 1) stop('input too long')
				if (!is.character(rObj)) stop('input must be a character representing a file path')
				tmp = fs::path_abs(fs::path_expand(rObj),getwd())
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFile',tmp))
			},
			RUntypedNa=function(rObj) {
				return(rJava::.jnew('uk/co/terminological/rjava/types/RUntypedNa'))
			},
			RFactorVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector'))
				if (!is.factor(rObj)) stop('expected a vector of factors')
				tmp = as.integer(rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RFactorVector', rJava::.jarray(tmp), rJava::.jarray(levels(rObj))))
			},
			RIntegerVector=function(rObj) {
				if (is.null(rObj)) return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector'))
				tmp = as.integer(rObj)
				if (any(rObj!=tmp,na.rm=TRUE)) stop('cannot coerce to integer: ',rObj)
				return(rJava::.jnew('uk/co/terminological/rjava/types/RIntegerVector',rJava::.jarray(tmp)))
			},
			RNamedList=function(rObj) {
				if (!is.list(rObj) | is.null(names(rObj))) stop ('expecting a named list')
				jout = rJava::.jnew('uk/co/terminological/rjava/types/RNamedList')
				lapply(names(rObj), function(name) {
					x = rObj[[name]]
					if (is.null(x)) tmp = self$.toJava$RNull(x)
					else if (is.data.frame(x)) tmp = self$.toJava$RDataframe(x)
					else if (is.list(x) & !is.null(names(x))) tmp = self$.toJava$RNamedList(x)
					else if (is.list(x)) tmp = self$.toJava$RList(x)
					else if (is.array(x) & is.numeric(x)) tmp = self$.toJava$RNumericArray(x)
					else if (length(x) == 1 & is.character(x)) tmp = self$.toJava$RCharacter(x)
					else if (length(x) == 1 & is.integer(x)) tmp = self$.toJava$RInteger(x)
					else if (length(x) == 1 & is.factor(x)) tmp = self$.toJava$RFactor(x)
					else if (length(x) == 1 & is.logical(x)) tmp = self$.toJava$RLogical(x)
					else if (length(x) == 1 & is.numeric(x)) tmp = self$.toJava$RNumeric(x)
					else if (length(x) == 1 & inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDate(x)
					else if (is.character(x)) tmp = self$.toJava$RCharacterVector(x)
					else if (is.integer(x)) tmp = self$.toJava$RIntegerVector(x)
					else if (is.factor(x)) tmp = self$.toJava$RFactorVector(x)
					else if (is.logical(x)) tmp = self$.toJava$RLogicalVector(x)
					else if (is.numeric(x)) tmp = self$.toJava$RNumericVector(x)
					else if (inherits(x,c('Date','POSIXt'))) tmp = self$.toJava$RDateVector(x)
					else stop ('unrecognised type: ',class(x),' with value ',x)
					rJava::.jcall(jout,returnSig='Luk/co/terminological/rjava/types/RObject;',method='put',name,rJava::.jcast(tmp, new.class='uk/co/terminological/rjava/types/RObject'))
				})
				return(jout)
			},
			MoreFeatureTest=function(rObj) return(rObj$.jobj)		)
		
		self$.fromJava = list(
			RNumericArray=function(jObj) {
				tmpVec = as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive'))
				tmpDim = as.integer(rJava::.jcall(jObj,returnSig='[I',method='rDim'))
			   if (length(tmpDim)==2) return(matrix(tmpVec,tmpDim))
				return(array(tmpVec,tmpDim))
			},
			RDate=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RDateVector=function(jObj) as.Date(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive'),'%Y-%m-%d'),
			RCharacterVector=function(jObj) as.character(rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rPrimitive')),
			FeatureTest=function(jObj) return(FeatureTest$new(jObj,self)),
			RNumeric=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='D',method='rPrimitive')),
			RLogical=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RFactor=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rLabel')),
			RNull=function(jObj) return(NULL),
			RLogicalVector=function(jObj) as.logical(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RCharacter=function(jObj) as.character(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive')),
			Serialiser=function(jObj) return(Serialiser$new(jObj,self)),
			String=function(jObj) return(as.character(jObj)),
			MinimalExample=function(jObj) return(MinimalExample$new(jObj,self)),
			FactoryTest=function(jObj) return(FactoryTest$new(jObj,self)),
			void=function(jObj) invisible(NULL),
			double=function(jObj) return(as.numeric(jObj)),
			RList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			},
			RNumericVector=function(jObj) as.numeric(rJava::.jcall(jObj,returnSig='[D',method='rPrimitive')),
			BounceTest=function(jObj) return(BounceTest$new(jObj,self)),
			int=function(jObj) return(as.integer(jObj)),
			boolean=function(jObj) return(as.logical(jObj)),
			RInteger=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='I',method='rPrimitive')),
			RBoundDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RDataframe=function(jObj) {
				convDf = eval(parse(text=rJava::.jcall(jObj,'rConversion', returnSig='Ljava/lang/String;')))
				groups = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='getGroups')
				return(dplyr::group_by(convDf(jObj),!!!sapply(groups,as.symbol)))
			},
			RUntypedNaVector=function(jObj) rep(NA, rJava::.jcall(jObj,returnSig='I',method='size')),
			RFile=function(jObj) {	fs::path(rJava::.jcall(jObj,returnSig='Ljava/lang/String;',method='rPrimitive'))},
			RUntypedNa=function(jObj) return(NA),
			RFactorVector=function(jObj) ordered(
				x = rJava::.jcall(jObj,returnSig='[I',method='rValues'),
				labels = rJava::.jcall(jObj,returnSig='[Ljava/lang/String;',method='rLevels')
			),
			RIntegerVector=function(jObj) as.integer(rJava::.jcall(jObj,returnSig='[I',method='rPrimitive')),
			RNamedList=function(jObj) {
				tmp = eval(parse(text=rJava::.jcall(jObj,'rCode', returnSig='Ljava/lang/String;')))
				return(tmp)
			},
			MoreFeatureTest=function(jObj) return(MoreFeatureTest$new(jObj,self))		)
	
		# initialise java class constructors and static method definitions
		
		self$MinimalExample = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/MinimalExample" , check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = MinimalExample$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			}
		)
		self$BounceTest = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/BounceTest" , check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = BounceTest$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			}
		)
		self$FeatureTest = list(
			new = function(logMessage) {
				# constructor
				# convert parameters to java
				tmp_logMessage = self$.toJava$String(logMessage);
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/FeatureTest" , tmp_logMessage, check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = FeatureTest$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			},
			demoStatic = function(message) {
				# copy parameters
				tmp_message = self$.toJava$String(message);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/FeatureTest", 
					returnSig = "V", 
					method = "demoStatic",
					tmp_message, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$void(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			diamonds = function() {
				# copy parameters
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/FeatureTest", 
					returnSig = "Luk/co/terminological/rjava/types/RDataframe;", 
					method = "diamonds", 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RDataframe(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			collider = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/FeatureTest", 
					returnSig = "Luk/co/terminological/rjava/types/RCharacter;", 
					method = "collider",
					tmp_message1,
					tmp_message2, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RCharacter(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			asyncStaticCountdown = function(label, rtimer=10) {
				# copy parameters
				tmp_label = self$.toJava$RCharacter(label);
				tmp_rtimer = self$.toJava$RInteger(rtimer);
				# statically construct a JFuture R6 object as return value.
				# this uses the JFuture constructor with a canonical  name as a parameter. 
				# in which case we must supply the api
				out = RFuture$new(
					r6obj = "uk.co.terminological.rjava.test.FeatureTest",
					converter = self$.fromJava$RCharacter,
					returnSig = "Luk/co/terminological/rjava/types/RCharacter;", 
					method = "asyncStaticCountdown",
					tmp_label,
					tmp_rtimer,
					api = self
				);
				# handle any messages and exceptions arising:
				self$printMessages();
				.jcheck();
				return(out);
			},
			asyncFactory = function() {
				# copy parameters
				# statically construct a JFuture R6 object as return value.
				# this uses the JFuture constructor with a canonical  name as a parameter. 
				# in which case we must supply the api
				out = RFuture$new(
					r6obj = "uk.co.terminological.rjava.test.FeatureTest",
					converter = self$.fromJava$FactoryTest,
					returnSig = "Luk/co/terminological/rjava/test/FactoryTest;", 
					method = "asyncFactory",
					api = self
				);
				# handle any messages and exceptions arising:
				self$printMessages();
				.jcheck();
				return(out);
			}		)
		self$MoreFeatureTest = list(
			new = function(message1, message2) {
				# constructor
				# convert parameters to java
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/MoreFeatureTest" , tmp_message1, tmp_message2, check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = MoreFeatureTest$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			},
			create = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/MoreFeatureTest", 
					returnSig = "Luk/co/terminological/rjava/test/MoreFeatureTest;", 
					method = "create",
					tmp_message1,
					tmp_message2, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$MoreFeatureTest(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			concat = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/MoreFeatureTest", 
					returnSig = "Luk/co/terminological/rjava/types/RCharacter;", 
					method = "concat",
					tmp_message1,
					tmp_message2, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RCharacter(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			collider = function(message1, message2) {
				# copy parameters
				tmp_message1 = self$.toJava$RCharacter(message1);
				tmp_message2 = self$.toJava$RCharacter(message2);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/MoreFeatureTest", 
					returnSig = "Luk/co/terminological/rjava/types/RCharacter;", 
					method = "collider",
					tmp_message1,
					tmp_message2, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RCharacter(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			}		)
		self$FactoryTest = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/FactoryTest" , check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = FactoryTest$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			}
		)
		self$Serialiser = list(
			new = function() {
				# constructor
				# convert parameters to java
				# invoke constructor method
				tmp_out = .jnew("uk/co/terminological/rjava/test/Serialiser" , check=FALSE);
				self$printMessages()
				.jcheck() 
				# convert result back to R (should be a identity conversion)
				tmp_r6 = Serialiser$new(
					tmp_out,
					self
				);
				return(tmp_r6)
			},
			serialiseDataframe = function(dataframe, filename) {
				# copy parameters
				tmp_dataframe = self$.toJava$RDataframe(dataframe);
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "V", 
					method = "serialiseDataframe",
					tmp_dataframe,
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$void(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			deserialiseDataframe = function(filename) {
				# copy parameters
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "Luk/co/terminological/rjava/types/RDataframe;", 
					method = "deserialiseDataframe",
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RDataframe(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			serialiseList = function(dataframe, filename) {
				# copy parameters
				tmp_dataframe = self$.toJava$RList(dataframe);
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "V", 
					method = "serialiseList",
					tmp_dataframe,
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$void(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			deserialiseList = function(filename) {
				# copy parameters
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "Luk/co/terminological/rjava/types/RList;", 
					method = "deserialiseList",
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RList(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			serialiseNamedList = function(dataframe, filename) {
				# copy parameters
				tmp_dataframe = self$.toJava$RNamedList(dataframe);
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "V", 
					method = "serialiseNamedList",
					tmp_dataframe,
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$void(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			},
			deserialiseNamedList = function(filename) {
				# copy parameters
				tmp_filename = self$.toJava$String(filename);
				# execute static call
				tmp_out = .jcall(
					"uk/co/terminological/rjava/test/Serialiser", 
					returnSig = "Luk/co/terminological/rjava/types/RNamedList;", 
					method = "deserialiseNamedList",
					tmp_filename, 
					check = FALSE);
				self$printMessages()
				.jcheck()
				# static methods cannot return themselves fluently, so this does not need to be checked for.
				# convert java object back to R. Wrapping in an R6 class as needed
				out = self$.fromJava$RNamedList(tmp_out);
				if(is.null(out)) return(invisible(out))
				return(out)
			}		)
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		# shutdown system console and logging
		.jcall("uk/co/terminological/rjava/RSystemOut", returnSig = "V", method = "release")
	}
))

JavaApi$singleton = NULL

JavaApi$get = function(logLevel = "INFO") {
	if (is.null(JavaApi$singleton)) {
		# set to non-null so that R6 constructor will work
		JavaApi$singleton = FALSE 
		JavaApi$singleton = JavaApi$new(logLevel)
	}
	return(JavaApi$singleton)
}

JavaApi$rebuildDependencies = function( ... ) {
	.startJvm()
	jars = .checkDependencies(nocache=TRUE, quiet=FALSE)
	if (!all(file.exists(jars))) {
		warning("The library has been rebuilt but there is still some missing dependencies: Out of the following")
		warning(paste0(jars,collapse="\n"))
		warning("The missing dependencies are:")
		warning(paste0(jars[file.exists(jars)],collapse="\n"))
		warning("Please double check this is not an issue with your connections etc")
		warning("The output of testRapi::JavaApi$rebuildDependencies(debug=TRUE) may help diagnose the problem")
	}
	
	return(jars)
}

JavaApi$installDependencies = function() {
	.startJvm()
	jars = .checkDependencies(nocache=FALSE, quiet=FALSE)
	.jaddClassPath(jars)
}

JavaApi$versionInformation = function() {
	out = list(
		package = "testRapi",
		r_package_version = "1.1.0",
		r_package_generated = "2024-05-16T16:22:15.419254778",
		java_library_version = "io.github.terminological:r6-generator-docs:1.1.0",
		maintainer = "rob@terminological.co.uk"
	)
	# try and get complilation information if library is loaded
	try({
		out$java_library_compiled = .jcall("uk/co/terminological/rjava/RLogController", returnSig = "S", method = "getClassBuildTime")
	}, silent=TRUE)
	return(out)
}

## package private utility functions for managing maven dependencies ----
# as this is generated code configuration is hard coded here
# i.e. these functions are specific for the configuration of this package.


.checkDependencies = function(nocache = FALSE, ...) {
	package_jar = .package_jars(package_name="testRapi",types="shaded")
	package_jar = package_jar[startsWith(fs::path_file(package_jar),"r6-generator-docs-1.1.0")]
	
	# Java dependencies
	# all java library code and dependencies have already been bundled into a single fat jar
	# compilation was done on the library developers machine and has no external dependencies
	jars = package_jar
	
	# find the jars that come bundled with the library:
	# and add any that have been resolved and downloaded by maven:
	return(jars)
}


.startJvm = function() {
	.start_jvm(debug=FALSE)
}

.message = function(msg) {
	if (!is.null(msg) && trimws(msg) != "") rlang::inform(paste0(trimws(msg),"\n"))
}
