# Generated by r6-generator-maven-plugin: do not edit by hand
# Contact: rc538@exeter.ac.uk
# A Test Library
#' R6 Bindings for Java Serialiser
#'
#' @description
#' Actually useful class which takes an R dataframe and a filename
#' 
#' This is a class of the testRapi generated R library.
#' 
#' Version: 0.0.0.9999
#' 
#' Generated: 2022-09-25T23:45:06.042097
#'
#' @details
	#' string and serialises the dataframe so it can be used natively in java
	#' for testing purposes.
#' @export
Serialiser = R6::R6Class("Serialiser", public=list(

	#' @field .api internal pointer to the library object.
	.api = NULL,

	#' @field .jobj internal pointer to the rJava reference to the java object.
	.jobj = NULL,


	#' @description
	#' Create a new Serialiser this is not for general use and instances should be created through the
	#' package api class. See example.
	#' @param jobj The internal rJava reference.
	#' @param api The R6 api library class.
	#' @return A new Serialiser object.
	#' @examples
	#' \dontrun{
	#' J = testRapi::JavaApi$get()
	#' # This constructor must be called via the JavaApi where an appropriate set of parameters must be provided.
	#' instance = J$Serialiser$new()
	#' }	
	initialize = function(jobj,api){
		self$.jobj = jobj;
		self$.api = api;
	},
	
	
	#' @description The output of toString() of this Serialiser
	print = function() {
		tmp_out = .jcall(self$.jobj, returnSig = "Ljava/lang/String;", method="toString");
		self$.api$printMessages()
		print(tmp_out)
		invisible(self)
	},
	
	#' @description The output of equals() of this Serialiser
	#' @param object The R6 instance to test for equality to this Serialiser  
	equals = function(object) {
		if (is.null(object$.jobj)) return(FALSE)
		return(self$.jobj$equals(object$.jobj))
	},
	
	#' @description Allow this object to be garbage collected.
	finalize = function() {
		self$.jobj = .jnull("uk/co/terminological/rjava/test/Serialiser")
		self$.jobj = NULL
		.jgc(R.gc = FALSE)
	}
))
