# Generated by r6-generator-maven-plugin: do not edit by hand
# This is a collection of the static methods described in the Java API
# and serves as an alternative R centric entry point of the testRapi generated R library.

# Version: 0.5.2
# Generated: 2022-08-15T15:23:02.145
# Contact: rc538@exeter.ac.uk

# FactoryTest class static methods ----


# BounceTest class static methods ----


# Serialiser class static methods ----


#' serialiseDataframe:
#' 
#' no title
#' @param dataframe - (java expects a RDataframe)
#' @param filename - (java expects a String)
#' @return void: 
#' 
#' @export
serialise_dataframe = function(dataframe, filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$serialiseDataframe(dataframe, filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' deserialiseDataframe:
#' 
#' no title
#' @param filename - (java expects a String)
#' @return RDataframe: 
#' 
#' @export
deserialise_dataframe = function(filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$deserialiseDataframe(filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' serialiseList:
#' 
#' no title
#' @param dataframe - (java expects a RList)
#' @param filename - (java expects a String)
#' @return void: 
#' 
#' @export
serialise_list = function(dataframe, filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$serialiseList(dataframe, filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' deserialiseList:
#' 
#' no title
#' @param filename - (java expects a String)
#' @return RList: 
#' 
#' @export
deserialise_list = function(filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$deserialiseList(filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' serialiseNamedList:
#' 
#' no title
#' @param dataframe - (java expects a RNamedList)
#' @param filename - (java expects a String)
#' @return void: 
#' 
#' @export
serialise_named_list = function(dataframe, filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$serialiseNamedList(dataframe, filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' deserialiseNamedList:
#' 
#' no title
#' @param filename - (java expects a String)
#' @return RNamedList: 
#' 
#' @export
deserialise_named_list = function(filename) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$Serialiser$deserialiseNamedList(filename)
	if(is.null(out)) return(invisible(out))
	return(out)
}


# FeatureTest class static methods ----


#' demoStatic:
#' 
#' Static methods are also supported. 
#' 
#' These are accessed through the
#' root of the R api, and as a functional interface
#' @param message a message - (java expects a String)
#' @return void: 
#' 
#' @examples
#' @export
demo_static = function(message) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$FeatureTest$demoStatic(message)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' diamonds:
#' 
#' The ggplot2::diamonds dataframe 
#' 
#' A copy serialised into java, using
#' RObject.writeRDS, saved within the jar file of the package, and exposed here
#' using RObject.readRDS.
#' @return RDataframe: 
#' the ggplot2::diamonds dataframe
#' @examples
#' expect_equal(diamonds(), ggplot2::diamonds)
#' @export
diamonds = function() {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$FeatureTest$diamonds()
	if(is.null(out)) return(invisible(out))
	return(out)
}


# MinimalExample class static methods ----


# MoreFeatureTest class static methods ----


#' create:
#' 
#' A static object constructor
#' @param message1 - the message to be printed - (java expects a RCharacter)
#' @param message2 - will be used for toString - (java expects a RCharacter)
#' @return R6 MoreFeatureTest object: 
#' A MoreFeatureTest R6 object
#' @examples
#' @export
create = function(message1, message2) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$MoreFeatureTest$create(message1, message2)
	if(is.null(out)) return(invisible(out))
	return(out)
}


#' concat:
#' 
#' no title
#' @param message1 - (java expects a RCharacter)
#' @param message2 - (java expects a RCharacter)
#' @return RCharacter: 
#' 
#' @export
concat = function(message1, message2) {
	# get the API singleton
	J = JavaApi$get()
	# execute the R6 function call with the same parameters
	out = J$MoreFeatureTest$concat(message1, message2)
	if(is.null(out)) return(invisible(out))
	return(out)
}





